MamaNieWie/MamaNieWie/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^', include('blog.urls')),
    url(r'^markdown/', include('django_markdown.urls')),
    url(r'^admin/', admin.site.urls),
]

r'^public/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}

MamaNieWie/blog/urls.py
__author__ = 'MagdaNT'
from django.conf.urls import url, patterns
from django.conf import settings
from . import views


app_name = 'blog'
urlpatterns = [
    url(r'^$', views.BlogIndex.as_view(), name='index'),
    url(r'^home/$', views.BlogIndex.as_view(), name='home'),
    url(r'^aboutus/$', views.AboutUs.as_view(), name='aboutus'),
    url(r'^expeditions/$', views.ExpeditionsView.as_view(), name='expeditions'),
    url(r'^gallery/$', views.VideoView.as_view(), name='video'),
    url(r'^contact/$', views.ContactView.as_view(), name='contact'),
    url(r'^posts/(?P<slug>[-\w]+)/$', views.PostView.as_view(), name='post'),
    url(r'^article/(?P<entry_slug>[-\w]+)/$', views.readmore, name='readmore'),
    url(r'^public/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
]
if settings.DEBUG:
    urlpatterns += patterns('',  url(r'^media/img/(?P<path>.*)$', 'django.views.static.serve',  {'document_root': settings.MEDIA_ROOT, }),)

MamaNieWie/blog/models.py
from __future__ import unicode_literals

from django.db import models

from filer.fields.file import FilerFileField
from filer.fields.image import FilerImageField
from django.conf import settings


class EntryQuerySet(models.QuerySet):
    def published(self):
        return self.filter(publish=True)



class Entry(models.Model):
    title = models.CharField(max_length=400)
    body = models.TextField()
    slug = models.SlugField(max_length=200, unique=True)
    publish = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    title_image = models.ImageField(upload_to=settings.MEDIA_URL, null=True)

    objects = EntryQuerySet.as_manager()

    def __unicode__(self):
        return self.title

    def get_image_filename(instance, filename):
        title =instance.entry.title
        return "media/%s" % filename


    def admin_thumbnail(self):
        return u'<img src="%s" />' % self.title_image.url
    admin_thumbnail.short_description = 'Thumbnail'
    admin_thumbnail.allow_tags = True

    class Meta:
        verbose_name = "Blog Entry"
        verbose_name_plural = "Blog Entries"
        ordering = ["-created"]

class Article_Image(models.Model):
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE)
    title = models.CharField(max_length=400)
    image = models.ImageField(upload_to=settings.MEDIA_URL, null=True)

MamaNieWie/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest
from django.shortcuts import get_object_or_404

from django.views import generic
from .models import Entry
from django.utils import timezone
from . import models

class BlogIndex(generic.ListView):
    queryset = models.Entry.objects.published()
    template_name = "blog/index.html"
    paginate_by = 4

class AboutUs(generic.ListView):
    queryset = models.Entry.objects.published()
    template_name = "blog/aboutus.html"
    paginate_by = 4

class ExpeditionsView(generic.ListView):
    queryset = models.Entry.objects.published()
    template_name = "blog/expeditions.html"
    paginate_by = 4

class VideoView(generic.ListView):
    queryset = models.Entry.objects.published()
    template_name = "blog/video.html"
    paginate_by = 2

# class PostView(generic.ListView):
#     queryset = models.Entry.objects.published()
#     template_name = "blog/post.html"
#     paginate_by = 4

class ContactView(generic.ListView):
    queryset = models.Entry.objects.published()
    template_name = "blog/contact.html"
    paginate_by = 2


def readmore(request, entry_slug):
    entry = get_object_or_404(Entry, slug=entry_slug)
    return render(request, 'blog/article.html', {
            'entry': entry,
            'error_message': "You didn't select a choice.",
        })


class PostView(generic.DetailView):
    template_name = 'blog/post.html'
    model = Entry

    def get_context_data(self, **kwargs):
        context = super(PostView, self).get_context_data(**kwargs)
        return context

MamaNieWie/blog/templates/blog/aboutus.html
<h1>Kontakt</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

MamaNieWie/blog/templates/blog/article.html
<!DOCTYPE html>
<html lang="en">
{% load django_markdown %}
<head>
	{% load staticfiles %}
	<title>entry.title</title>
	<meta charset="utf-8">
	<!--<meta name="author" content="ntmagda">-->
	<!--<link rel="stylesheet" type="text/css" href="{% static 'css_templates/css/reset.css' %}">-->
	<!--<link rel="stylesheet" type="text/css" href="{% static 'css_templates/css/main.css' %}">-->
</head>
<body>
        <article>
            <div class="article_image">
                <a href="">
                    <img src="{% static entry.title_image %}" alt="" title="">
                </a>
            </div>
            <div class="post">
                <h1 class="title">
                    {{ entry.title }}
                </h1>
                <p class ="meta"> {{entry.created}}</p>
                {{entry.body|markdown }}
            </div>
        </article>
	<footer>
		<div class="wrapper">
		</div>
	</footer>

</body>
</html>

MamaNieWie/blog/templates/blog/contact.html
<h1>Kontakt</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

MamaNieWie/blog/templates/blog/expeditions.html
<!DOCTYPE html>
<html lang="en">
{% load django_markdown %}
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>Expeditions</title>

	<link rel="stylesheet" type="text/css" href="{% static 'css_templates/css/mystyle1.css' %}">
</head>
<body>
<div class="blog_title">
		Mama nie wie, że sie wspinam
	</div>
	<header>
			<nav>
				<ul class="main_nav">
                    <li><a href="{% url 'blog:home' 		%}">Home</a></li>
					<li><a href="{% url 'blog:aboutus' 		%}">O nas</a></li>
					<li><a href="{% url 'blog:expeditions' 	%}">Wyprawy</a></li>
					<li><a href="{% url 'blog:video' 		%}">Filmy</a></li>
					<li><a href="{% url 'blog:contact' 		%}">Kontakt</a></li>
				</ul>
			</nav>
			<!--<div class = "blog_logo">-->
			<!--</div>-->

	</header>


{% for object in object_list %}
<article>
    <div class="article_image">
            <a href="#">
                <img src="{% static object.title_image %}" alt="" title="">
            </a>
    </div>
    <div class="post">
        <h1 class="title">
            <a href="#">{{ object.title }}</a>
        </h1>
        <p class ="meta"> {{object.created}}</p>
        {{object.body|markdown|truncatewords:50 }}
        <a class="read_more" href="{% url 'blog:readmore' object.slug %}">Continue Reading <i class="read_more_arrow"></i> </a>
    </div>
</article>
{% endfor %}


</body>
</html>

MamaNieWie/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
{% load django_markdown %}
<head>
	{% load staticfiles %}
	<title>Mama nie wie, że się wspinam</title>
	<meta charset="utf-8">
	<meta name="author" content="ntmagda">
	<link rel="stylesheet" type="text/css" href="{% static 'css_templates/css/mystyle1.css' %}">
    <!-- jQuery library (served from Google) -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
</head>
<body>
	<div class="blog_title">
		Mama nie wie, że sie wspinam
	</div>
	<header>
			<nav>
				<ul class="main_nav">
					<li><a href="{% url 'blog:home' 		%}">Home</a></li>
					<li><a href="{% url 'blog:aboutus' 		%}">O nas</a></li>
					<li><a href="{% url 'blog:expeditions' 	%}">Wyprawy</a></li>
					<li><a href="{% url 'blog:video' 		%}">Filmy</a></li>
					<li><a href="{% url 'blog:contact' 		%}">Kontakt</a></li>
				</ul>
			</nav>
	</header>


	<section class="main wrapper">

		<img class="svg" src="{% static 'map/map1.svg' %}">

	<footer>
		<div class="wrapper">
		</div>
	</footer>
	</section>

	<!--<div id="popups">-->
		<div class = "testuj">
			Cokolwiek
		</div>
	<!--</div>-->

	<script>
		var pin_slugs = [];
        var pin_thumbnails = [];
		{% for object in object_list %}
			pin_slugs.push( "{{ object.slug }}" );
            pin_thumbnails.push("{{ object.title_image }}")
		{% endfor %}

	</script>
	<script src="{% static 'js/create_pin_divs.js' %}"></script>
	<script src="{% static 'js/click_on_pin.js' %}"></script>

</body>
</html>

MamaNieWie/blog/templates/blog/post.html
<html lang="en">
{% load django_markdown %}
<head>
	{% load staticfiles %}
    <title>Mama nie wie, że się wspinam</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css_templates/css/mystyle1.css' %}">


</head>

<body>
	<div class="blog_title">
		Mama nie wie, że sie wspinam
	</div>
	<header>
			<nav>
				<ul class="main_nav">
					<li><a href="{% url 'blog:home' 		%}">Home</a></li>
					<li><a href="{% url 'blog:aboutus' 		%}">O nas</a></li>
					<li><a href="{% url 'blog:expeditions' 	%}">Wyprawy</a></li>
					<li><a href="{% url 'blog:video' 		%}">Filmy</a></li>
					<li><a href="{% url 'blog:contact' 		%}">Kontakt</a></li>
				</ul>
			</nav>
			<!--<div class = "blog_logo">-->
			<!--</div>-->

	</header>

        <section class="content">
			<article>
				<div class="article_image">
						<a href="#">
							<img src="{% static object.title_image %}" alt="" title="">
						</a>
				</div>
				<div class="post">
					<h1 class="title">
						<a href="#">{{ object.title }}</a>
					</h1>
					<p class ="meta"> {{object.created}}</p>
					{{object.body|markdown|truncatewords:50 }}
					<a class="read_more" href="{% url 'blog:readmore' object.slug %}">Continue Reading <i class="read_more_arrow"></i> </a>
				</div>
			</article>
        </section>

</body>

</html>

MamaNieWie/blog/templates/blog/test.html
<!DOCTYPE html>
<html lang="en">
{% load django_markdown %}
<head>
	{% load staticfiles %}
	<title>Mama nie wie, że się wspinam</title>
	<meta charset="utf-8">
	<meta name="author" content="ntmagda">
	<link rel="stylesheet" type="text/css" href="{% static 'css_templates/css/mystyle1.css' %}">
    <!-- jQuery library (served from Google) -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <!-- bxSlider Javascript file -->
    <script src="{% static 'carousel/jquery.bxslider.min.js' %}"></script>
	<script src="{% static 'js/click_on_pin.js' %}"></script>
	<script>
		var pin_titles = [];
		{% for object in object_list %}
			pin_titles.push( "{{ object.title }}" );
		{% endfor %}

		$('#body').append("<div class='dupa'>content</div>");
	</script>
	<script src="{% static 'js/create_pin_divs.js' %}"></script>

    <!-- bxSlider CSS file -->
    <link href="{% static 'carousel/jquery.bxslider.css' %}" rel="stylesheet" />

	<script type="text/javascript" charset="utf-8">

    $(document).ready(function(){
        $('.bxslider').bxSlider({
          minSlides: 2,
          maxSlides: 2,
          slideWidth: 900,
          slideMargin: 0,
          adaptiveHeight: true,
    });
    });

    </script>
</head>
<body>
	<div class="blog_title">
		Mama nie wie, że sie wspinam
	</div>
	<header>
			<nav>
				<ul class="main_nav">
					<li><a href="{% url 'blog:home' 		%}">Home</a></li>
					<li><a href="{% url 'blog:aboutus' 		%}">O nas</a></li>
					<li><a href="{% url 'blog:expeditions' 	%}">Wyprawy</a></li>
					<li><a href="{% url 'blog:video' 		%}">Filmy</a></li>
					<li><a href="{% url 'blog:contact' 		%}">Kontakt</a></li>
				</ul>
			</nav>
			<!--<div class = "blog_logo">-->
			<!--</div>-->
	</header>



     <!--<ul class="bxslider">-->
				  <!--{% for object in object_list %}-->
					<!--<li>-->
                        <!--<div class = "slide">-->
                           <!--<img src="{% static object.title_image %}">-->
                           <!--<span class = "part_of_post">-->
                               <!--<h1 class="title">-->
                                    <!--{{ object.title }}-->
                               <!--</h1>-->
                               <!--<p class = "article_text">-->
                                <!--&lt;!&ndash;<p class ="meta"> {{object.created}}</p>&ndash;&gt;-->
                                <!--{{object.body|markdown|truncatewords:50 }}-->
                               <!--</p>-->
                            <!--</span>-->
                            <!--&lt;!&ndash;<a class="read_more" href="{% url 'blog:readmore' object.slug %}">Continue Reading <i class="read_more_arrow"></i> </a>&ndash;&gt;-->
                        <!--</div>-->
					<!--</li>-->
				  <!--{% endfor %}-->
			  <!--</ul>-->
	<section class="main wrapper">

		<img class="svg" src="{% static 'map/map1.svg' %}">



		<!--</section>&lt;!&ndash; Content End &ndash;&gt;-->
		<!--<aside class="sidebar">-->
			<!--<section class="widget">-->
				<!--<h3 class="widget-title">About Blogin.</h3>-->
				<!--<div class="textwidget">-->
					<!--<p>Duis aute irure dolor in rhenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p>-->
					<!--<p>Excepteur sint occaecat sunt in culpa qui officia deserunt mollit anim id est laborum.</p>-->
				<!--</div>-->
			<!--</section>-->

			<!--<section class="widget">-->
				<!--<h3 class="widget-title">Search.</h3>-->
				<!--<form class="search_widget">-->
					<!--<input type="text" id="search-field" class="search-field" placeholder="What are you looking for?"/>-->
				<!--</form>-->
			<!--</section>-->

			<!--<section class="widget">-->
				<!--<a href="#">-->
					<!--&lt;!&ndash;<img src="{% static 'css_templates/img/ads.jpg' %}" alt="" title="">&ndash;&gt;-->
				<!--</a>-->
			<!--</section>-->
		<!--</aside>&lt;!&ndash; aside(sidebar) End &ndash;&gt;-->

		<!--<nav class="pagination">-->
			<!--<a href="#" class="previous"><i></i>Previous</a>-->
			<!--<a href="#" class="next">Next<i></i></a>-->
		<!--</nav>&lt;!&ndash; pagination End &ndash;&gt;-->


	<footer>
		<div class="wrapper">
		</div>
	</footer>
	</section>



</body>
</html>

MamaNieWie/blog/templates/blog/video.html
<!DOCTYPE html>
<html lang="en">
<html lang="en">
{% load django_markdown %}
<head>
	{% load staticfiles %}
	<title>Galleria</title>
	<meta charset="utf-8">
	<meta name="author" content="ntmagda">
	<link rel="stylesheet" type="text/css" href="{% static 'css_templates/css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css_templates/css/main.css' %}">
</head>
<body>

<section class="main gallery">
    <div id="content">
    <ul id="picturelist">
      <li>a tree<a href="#"><img src="{% static 'css_templates/img/climb5.png' %}" alt="a tree"/></a></li>
      <li>the sea<a href="#"><img src="{% static 'css_templates/img/climb5.png' %}" alt="the sea"/></a></li>
      <li>the forest<a href="#"><img src="{% static 'css_templates/img/climb5.png' %}" alt="the forest"/></a></li>
      <li>a bunch of orange flowers<a href="#"><img src="{% static 'css_templates/img/climb5.png' %}" alt="a bunch of orange flowers"/></a></li>
      <li>a turtle in the sea<a href="#"><img src="{% static 'css_templates/img/climb5.png' %}" alt="a turtle in the sea"/></a></li>
      <li>a garden/jungle thing<a href="#"><img src="{% static 'css_templates/img/climb5.png' %}" alt="a garden/jungle thing"/></a></li>
      <li>an oryx antelope in the desert<a href="#"><img src="{% static 'css_templates/img/climb5.png' %}" alt="an oryx antelope in the desert"/></a></li>
      <li>mesas in the desert<a href="#"><img src="{% static 'css_templates/img/climb5.png' %}" alt="mesas in the desert"/></a></li>
    </ul>
  </div>
</section><!-- Content End -->




</body>
</html>